### ISSUE TITLE
GH_TOKEN unbound for organization account repo

### ISSUE THREAD

**Issue by jangorecki** [csgillespie/dratTravis#2]
Hi,
I've followed [CombiningDratAndTravis vignette](https://eddelbuettel.github.io/drat/CombiningDratAndTravis.html) and with minor adjustment (I had to explicitly declare `PKG_TARBALL` in deploy.sh) I've successfully setup auto push to drat on my user account repo, see [build details, line 3269](https://travis-ci.org/jangorecki/data.table/builds/112159566).
Once I've switched target repo from user's account to organization account, so I can PR it to upstream, it failed to work with `deploy.sh: line 18: GH_TOKEN: unbound variable` error, see [build log](https://travis-ci.org/Rdatatable/data.table/builds/112172795).
I read somewhere I need write access to the organization repo and my user's GH Token will work (can't find that article now). I have write access to repo and my GH Token didn't work.
Is there any specific way to setup auto push drat on organization repo? Should I use token from my user account? If so any reason why GH Token is not recognized?
Thanks in advance

**Comment by csgillespie** [comment]
You can certainly auto push on an organization repo (I do at https://github.com/rcourses). 

I think your problem is that you've copied your personal token from jangorecki/data.table to Rdatatable/data.table

You need to generate another token specificially for the Rdatatable account

**Comment by jangorecki** [comment]
@csgillespie OK, thanks for feedback. You are correct.
