### ISSUE TITLE
additional test on TRAVIS_REPO_SLUG to proceed with deploy.sh

### ISSUE THREAD

**Issue by jangorecki** [csgillespie/dratTravis#3]
Additional test could be useful, for example using `TRAVIS_REPO_SLUG` variable:

> The slug (in form: `owner_name/repo_name`) of the repository currently being built. (for example, “travis-ci/travis-build”).

Kind of

```
- test $TRAVIS_REPO_SLUG == "csgillespie/dratTravis" && test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash deploy.sh
```

This will ensure that if somebody will fork your repository it will not try to push from his account travis build, which will fail anyway due too invalid GH Token. If somebody want to setup own drat+travis then he needs to update GH token anyway, so can also update `TRAVIS_REPO_SLUG`. IMO better to not run deploy.sh if it is going to fail.

**Comment by csgillespie** [comment]
I agree. I'll try and add it in the near future.
